# Generated by Django 4.1.3 on 2022-11-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200510_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seller_contact',
            field=models.CharField(default=714062167, max_length=100),
            preserve_default=False,
        ),
    ]
